<link rel="stylesheet" href="<?php echo base_url() ?>assets/css/linearicons.css">
<link rel="stylesheet" href="<?php echo base_url() ?>assets/css/font-awesome.min.css">
<link rel="stylesheet" href="<?php echo base_url() ?>assets/css/bootstrap.css">
<link rel="stylesheet" href="<?php echo base_url() ?>assets/css/magnific-popup.css">
<link rel="stylesheet" href="<?php echo base_url() ?>assets/css/nice-select.css">
<link rel="stylesheet" href="<?php echo base_url() ?>assets/css/animate.min.css">
<link rel="stylesheet" href="<?php echo base_url() ?>assets/css/owl.carousel.css">
<link rel="stylesheet" href="<?php echo base_url() ?>assets/css/jquery-ui.css">
<link rel="stylesheet" href="<?php echo base_url() ?>assets/css/main.css">